# Generated by Django 4.0.4 on 2022-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=2, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
